#!/usr/bin/env node

// This is a Node.js script that interacts with the ChatGPT server
// using Puppeteer, a Node.js library for controlling a headless
// Chrome or Chromium browser. The script provides two modes of
// operation: "send" mode and "receive" mode. 

// In send mode, the script reads a query from standard input, sends
// the query to the ChatGPT server via the browser, and exits. 

// In receive mode, the script waits for a reply from the ChatGPT
// server via the browser, extracts the reply from the browser's HTML,
// converts it to plain text using the html-to-text Node.js library,
// and outputs the plain text to standard output. 

// The script also provides an optional "-i" mode to reload the
// ChatGPT page in the browser. 

// https://pptr.dev/
const puppeteer = require('puppeteer-core');
const convert = require('html-to-text');
const exec = require('child_process').exec

// This function is used for debugging purposes.
function die (msg='aborted') {
    console.log('** ', msg);
    process.exit(1);
}
    
async function sleep (ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
async function connect_to_browser () {
    for (let n = 0; n < 3; n++) {
	try {
	    // FIXME: Port number should be configurable.
	    let browser = await puppeteer.connect({
		browserURL: 'http://localhost:9000',
		defaultViewport: null,
	    });
	    return browser;
	}
	catch (err) {
	    exec('google-chrome --remote-debugging-port=9000', function (error, stdout, stderr) {});
	    await sleep(500);
	}
    }
}

async function current_page () {
    const browser = await connect_to_browser();
    const pages = await browser.pages();
    for (const page of pages) {
	// FIXME: Avoid hard-coding.
	const url = page.url();
	if (url.indexOf('chatgpt.com') > 0) {
	    await page.bringToFront();
	    return page;
	}
    }
    // Open ChatGPT if not already visiting.
    let page = pages[0];
    await page.bringToFront();
    await page.goto('https://chatgpt.com/');
    return page;
}

async function get_text (page, elem) {
    let html = await page.evaluate(el => el.innerHTML, elem);
    let text = convert.convert(html, {
        preserveNewlines: true,
        wordwrap: false,
    });
    return text;
}

async function send_query (query) {
    const page = await current_page();
    await page.$eval('#prompt-textarea > p',
		     (el, str) => el.innerText = str, query);
    await sleep(100);
    // Note: Submit button has the data-testid field.
    const button = await page.waitForSelector('button[data-testid="send-button"]');
    await button.click();

    let elem;
    while (true) {
	let elems = await page.$$('div[data-message-author-role="assistant"]');
	elem = elems[elems.length - 1];
	let text = await get_text (page, elem);
	if (text.length < 500)
	    break;
	await sleep(200);
    }

    let last_reply = '';
    let count = 0;
    while (count < 10) {
	reply = await get_text (page, elem);
	reply = reply.replace(/\n/g, '\\n\n');
	console.log(reply.length, last_reply.length);
	if (reply.length > last_reply.length) { // Any addition?
	    console.log(reply);
	    last_reply = reply;
	} else {
	    count++;
	}
	await sleep(200);
    }
}

// argv[2] is the first user-specified argument.
const mode = process.argv[2];

if (mode == '-i') {
    (async () => {
	const page = await current_page();
	process.exit(0);
    })();
} else if (mode == '-q') {
    (async () => {
	const query = process.argv[3]
	await send_query(query);
	process.exit(0);
    })();
}
